pom.xml
zipkin-java-jdbc/pom.xml
zipkin-java-jdbc/src/main/java/io/zipkin/jdbc/JDBCSpanStore.java
zipkin-java-server/pom.xml
zipkin-java-server/src/main/java/io/zipkin/ZipkinServer.java
zipkin-java-spanstore/pom.xml
zipkin-java-spanstore/src/main/java/io/zipkin/spanstore/InMemorySpanStore.java
zipkin-java-spanstore/src/main/java/io/zipkin/spanstore/QueryException.java
zipkin-java-spanstore/src/main/java/io/zipkin/spanstore/QueryRequest.java
zipkin-java-spanstore/src/main/java/io/zipkin/spanstore/SpanStore.java
zipkin-java-spanstore/src/test/java/io/zipkin/spanstore/InMemoryScalaSpanStoreTest.java
zipkin-java-spanstore/src/test/java/io/zipkin/spanstore/InMemorySpanStoreTest.java
zipkin-java-spanstore/src/test/java/io/zipkin/spanstore/ScalaSpanStoreAdapter.java
zipkin-java-spanstore/src/test/java/io/zipkin/spanstore/SpanStoreTest.java

This replaces `ZipkinQuery & Consumer<List<Span>>` with `SpanStore`,
simplifying type signatures and exposing the storage layer in its
entirety.
In the scala project, there's a SpanStore contract, a read/write api
similar to a union of the Scribe and ZipkinQuery interfaces. The java
project expects scribe to fade into an implementation detail. However,
there's still value in encapsulating the storage aspect, including
writes, as that's how we can eventually replace the storage layer in
any listener. It also helps us to write tests.
The down-side is that in many cases, the code to store is far simpler
than the code to query. Joining the two apis means you need to bring
along both when you want either. I consider this a minor concern, as
the code is still reasonably small and would have the …

Renames zipkin-query to zipkin-spanstore

---

zipkin-java-interop/src/test/java/io/zipkin/jdbc/JDBCTestGraph.java
zipkin-java-jdbc/src/main/java/io/zipkin/jdbc/JDBCSpanStore.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinQueryApiV1.java
zipkin-java-server/src/main/resources/zipkin-server.yml

This corrects some small differences in environment variables and
defaults vs upstream. More importantly, it fixes a bug where limit
applied to spans as opposed to traces.

Aligns JDBC behavior with upstream

---

zipkin-java-core/src/main/java/io/zipkin/Codec.java
zipkin-java-core/src/main/java/io/zipkin/Dependencies.java
zipkin-java-core/src/main/java/io/zipkin/SpanStore.java
zipkin-java-core/src/main/java/io/zipkin/internal/JsonCodec.java
zipkin-java-core/src/main/java/io/zipkin/internal/Pair.java
zipkin-java-core/src/main/java/io/zipkin/internal/ThriftCodec.java
zipkin-java-core/src/test/java/io/zipkin/CodecTest.java
zipkin-java-core/src/test/java/io/zipkin/DependenciesTest.java
zipkin-java-interop/src/test/java/io/zipkin/jdbc/JDBCScalaSpanStoreTest.java
zipkin-java-jdbc/src/main/java/io/zipkin/jdbc/JDBCSpanStore.java
zipkin-java-server/src/main/java/io/zipkin/server/InMemorySpanStore.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinQueryApiV1.java

This allows you to see the dependency-graph without hadoop or otherwise.
This shows services which are linked by parentId, with a count of how
many spans were logged. This will only show traces with at least one
edge (child), even if that edge is a loopback.
The UI remains unchanged: the point of the line corresponds with the amount of traffic.

Adds on-demand dependencies support to zipkin-jdbc

---

zipkin-java-core/src/main/java/io/zipkin/Codec.java
zipkin-java-core/src/main/java/io/zipkin/internal/JsonCodec.java
zipkin-java-core/src/main/java/io/zipkin/internal/ThriftCodec.java
zipkin-java-core/src/test/java/io/zipkin/CodecTest.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinQueryApiV1.java

This moves codec of `List<Span>` to a top-level type in preparation of a
POST endpoint that accepts either in thrift or json.

Adds span list codec for json and thrift

---

zipkin-java-server/pom.xml
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinQueryApiV1.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinServerConfiguration.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinSpanWriter.java
zipkin-java-server/src/test/java/io/zipkin/server/ZipkinServerIntegrationTests.java

With no content type (or application/json) we accept JSON, and with
content-type=application/x-thrift we accept Thrift. In both cases
a List<Span> is POSted to /api/v1/spans. The endpoint returns
immediately with a 202 (ACCEPTED) and the spans are written to the
store in an @Async service method.

Add support for HTTP POST /api/v1/spans

---

zipkin-java-server/Dockerfile
zipkin-java-server/pom.xml

With a default docker-machine on a Mid-2014 Macbook Pro, and the default
docker-compose file. I was getting consistent 16s startup, as reported
by Spring Boot's output.
My suspicion was that this was packaging related, as there are many jars
inside the default assembly of Spring Boot. Since Boot does classpath
scanning, it would need to unpack these in order to progress.
@dsyer found that if we do the unpacking at install time, we can reduce
the impact. I verified this, by running the same operation. I'm now
getting consistent 14s ranges on the same docker-machine.
There's other optimizations left. For example, if you remove the
database property and delete the Hikari dep from the pom (so that boot
can't find it), another 2-3 seconds are saved in an otherwise identical
docker-machine. …

Unzips all jar and removes actuator, reducing bootstrap time

---

zipkin-java-core/src/main/java/io/zipkin/internal/JsonCodec.java
zipkin-java-core/src/main/java/io/zipkin/internal/Pair.java
zipkin-java-interop/pom.xml
zipkin-java-jdbc/src/main/java/io/zipkin/jdbc/JDBCSpanStore.java
zipkin-java-server/Dockerfile

Notably, this updates to properly render the dependency view, based on some things mdsol noticed. This also shows earlier work, where we can display the JDBC destination IP (as it is logged as a "sa" annotation)

Updates to 1.18.1 plus some tidies

---

docker-compose.yml
zipkin-java-interop/pom.xml
zipkin-java-server/Dockerfile

Starting with zipkin 1.19.1, the UI process (zipkin-web) no longer
depends on scribe for self-tracing. This cuts the minimum deployment to
2 processes, which happen to be the smallest.
The net effect is a simpler starter architecture, which takes less time
to understand, less MB to download, and less memory to run.

Updates to upstream 1.19.1, eliminating the collector dependency

---

zipkin-java-core/src/main/java/io/zipkin/Codec.java
zipkin-java-core/src/main/java/io/zipkin/internal/JsonCodec.java
zipkin-java-core/src/main/java/io/zipkin/internal/ThriftCodec.java
zipkin-java-core/src/main/java/io/zipkin/internal/Util.java
zipkin-java-core/src/test/java/io/zipkin/CodecTest.java
zipkin-java-core/src/test/java/io/zipkin/internal/UtilTest.java
zipkin-java-interop/src/main/java/io/zipkin/interop/ScalaSpanStoreAdapter.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinQueryApiV1.java

Codec had a larger interface than needed, and instances were used
directly. This moves to an interface for reasons including preparation
of codec tracing via dependency injection.

Moves codec ops to an interface in preparation of tracing

---

zipkin-java-server/pom.xml
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinServer.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinServerConfiguration.java
zipkin-java-server/src/main/java/io/zipkin/server/brave/BootstrapTrace.java
zipkin-java-server/src/main/java/io/zipkin/server/brave/TraceWritesSpanStore.java

The scala project logs a local trace of bootstrap, to serve as an
example of how to do that. This adds a local trace, including the same
start signal (init), but spring-boot specific annotations for lifecycle
events.
This also adds a SpanStore tracer (except for writes), to show an
example of how to trace a local component
Here's an example bootstrap trace from docker on my macbook pro:
And here's an example of how much time zipkin spends actually retrieving spans (vs http/api overhead):
This change is awaiting a release of brave 3.2

Adds bootstrap and codec to self-tracing

---

docker-compose.yml
pom.xml
zipkin-java-interop/pom.xml
zipkin-java-server/Dockerfile
zipkin-java-server/README.md
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinServerProperties.java
zipkin-java-server/src/main/resources/zipkin-server.yml

This adds docs regarding which environment variables are supported. It
also corrects `MYSQL_PORT` which is actually `MYSQL_TCP_PORT`.

Adjusts environment variables to match zipkin-scala and adds docs

---

pom.xml
src/etc/header.txt

Per CONTRIBUTING.md, license headers are updatable via `./mvnw com.mycila:license-maven-plugin:format`. The impact of this config is that the first update to a file per year needs to change the range. Ex. `2015` to `2015-2016`

Automagically deal with copyright year updates

---

.travis.yml
pom.xml
zipkin-java-benchmarks/README.md
zipkin-java-benchmarks/pom.xml
zipkin-java-benchmarks/src/main/java/io/zipkin/benchmarks/BeforeTheFactSamplingBenchmarks.java

Zipkin v1 uses statistical sampling, both locally in instrumentation and
at the collection-tier. For the zipkin-server to be compatible with the
scala collector, we need to implement the same sampling approach.
Specifically, this is to support the `COLLECTOR_SAMPLE_RATE` property.
A follow-up change will implement a collector, using the
`compareTraceId_mostNegativeNumberDefense` measured here. Other
algorithms are measured for the sake of comparison.
See #52
Here are example results from my mid 2014 MBP
```
Benchmark                                                                            (traceId)   Mode  Cnt    Score    Error   Units
BeforeTheFactSamplingBenchmarks.compareCounter                            -9223372036854775808  thrpt   15  125.485 ±  6.782  ops/us …
```

Adds BeforeTheFactSamplingBenchmarks to support future samplers

---

zipkin-java-benchmarks/src/main/java/io/zipkin/benchmarks/BeforeTheFactSamplingBenchmarks.java
zipkin-java-core/pom.xml
zipkin-java-core/src/main/java/io/zipkin/SpanStore.java
zipkin-java-core/src/main/java/io/zipkin/TraceIdSampler.java
zipkin-java-core/src/test/java/io/zipkin/TraceIdSamplerTest.java
zipkin-java-interop/src/main/java/io/zipkin/interop/ScalaSpanStoreAdapter.java
zipkin-java-interop/src/test/java/io/zipkin/SpanStoreTest.java
zipkin-java-jdbc/src/main/java/io/zipkin/jdbc/JDBCSpanStore.java
zipkin-java-server/README.md
zipkin-java-server/src/main/java/io/zipkin/server/InMemorySpanStore.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinQueryApiV1.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinServerConfiguration.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinServerProperties.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinSpanWriter.java
zipkin-java-server/src/main/java/io/zipkin/server/brave/SpanStoreSpanCollector.java
zipkin-java-server/src/main/java/io/zipkin/server/brave/TraceWritesSpanStore.java
zipkin-java-server/src/main/resources/zipkin-server.yml
zipkin-java-server/src/test/java/io/zipkin/server/ZipkinSpanWriterTest.java

This introduces a port of the zipkin-scala sampler as TraceIdSampler.
This is used to implement the `COLLECTOR_SAMPLE_RATE` env property.
In order to make filtering easy and portable with language level 7, this
changes `SpanStore.accept` to take an iterator as opposed to a list.
Fixes #52

Honor COLLECTOR_SAMPLE_RATE with TraceIdSampler

---

zipkin-java-core/src/main/java/io/zipkin/SpanStore.java
zipkin-java-interop/src/main/java/io/zipkin/interop/ScalaDependencyStoreAdapter.java
zipkin-java-interop/src/main/java/io/zipkin/interop/ScalaSpanStoreAdapter.java
zipkin-java-jdbc/src/main/java/io/zipkin/jdbc/JDBCSpanStore.java
zipkin-java-server/src/main/java/io/zipkin/server/InMemorySpanStore.java
zipkin-java-server/src/main/java/io/zipkin/server/brave/TraceWritesSpanStore.java

Closeable isn't the only way to close things, and in reality we weren't
doing anything with it. This punts the decision on how to close
resources to implementing types.
See https://github.com/openzipkin/zipkin/issues/584

Removes Closeable contract from SpanStore

---

zipkin-java-benchmarks/README.md
zipkin-java-benchmarks/src/main/java/io/zipkin/benchmarks/BeforeTheFactSamplingBenchmarks.java

Good suggestion by @bensigelman
Here are sample results, first w/ default (single thread). Secondly 4 (same as my core count)
```
Benchmark                                                                            (traceId)   Mode  Cnt    Score    Error   Units
BeforeTheFactSamplingBenchmarks.compareCounter                            -9223372036854775808  thrpt   15  132.766 ±  2.285  ops/us
BeforeTheFactSamplingBenchmarks.compareCounter                             1234567890987654321  thrpt   15  133.453 ±  1.911  ops/us
BeforeTheFactSamplingBenchmarks.compareRandomNumber                       -9223372036854775808  thrpt   15   98.178 ±  3.563  ops/us
BeforeTheFactSamplingBenchmarks.compareRandomNumber                        1234567890987654321  thrpt   15   96.590 ±  1.774  ops/us …
```

Adds instructions for adding contention to benchmarks

---

zipkin-java-core/src/main/java/io/zipkin/Annotation.java
zipkin-java-core/src/main/java/io/zipkin/DependencyLink.java
zipkin-java-core/src/main/java/io/zipkin/Endpoint.java
zipkin-java-interop/src/main/java/io/zipkin/interop/ScalaDependencyStoreAdapter.java
zipkin-java-interop/src/main/java/io/zipkin/interop/ScalaSpanStoreAdapter.java
zipkin-java-jdbc/src/main/java/io/zipkin/jdbc/JDBCSpanStore.java
zipkin-java-jdbc/src/main/java/io/zipkin/jdbc/internal/generated/Tables.java
zipkin-java-jdbc/src/main/java/io/zipkin/jdbc/internal/generated/Zipkin.java
zipkin-java-jdbc/src/main/java/io/zipkin/jdbc/internal/generated/tables/ZipkinAnnotations.java
zipkin-java-jdbc/src/main/java/io/zipkin/jdbc/internal/generated/tables/ZipkinSpans.java
zipkin-java-server/src/main/java/io/zipkin/server/EnableZipkinServer.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinQueryApiV1.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinServerConfiguration.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinServerProperties.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinSpanWriter.java
zipkin-java-server/src/main/java/io/zipkin/server/brave/ApiTracerConfiguration.java
zipkin-java-server/src/main/java/io/zipkin/server/brave/BraveConfiguration.java
zipkin-java-server/src/main/java/io/zipkin/server/brave/JDBCTracerConfiguration.java
zipkin-java-server/src/main/java/io/zipkin/server/brave/SpanStoreSpanCollector.java
zipkin-java-server/src/test/java/io/zipkin/server/ZipkinServerIntegrationTests.java

[Spring Framework style guide](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Code-Style) requires folks to always qualify fields
with `this.`. This project isn't a part of the spring framework, nor
derives it style from that.
Square and Google style (from which it derives) does not require such
qualification. I've contributed to projects from many orgs, and Spring
is the only place I've seen this. I don't think it is a stretch to call
this unconventional.
Unconventional is fine, when it improves the experience of development.
Writing much of the code in this codebase, I've found the unnecessary
qualification to cause quite the opposite. It is a cognitive break,
where I wonder what is special which requires this qualification? Other
times, it intrudes on …

Fixes imports per style and removes unnecessary "this" qualification

---

zipkin-java-core/src/main/java/io/zipkin/Codec.java
zipkin-java-core/src/main/java/io/zipkin/internal/JsonCodec.java
zipkin-java-core/src/main/java/io/zipkin/internal/ThriftCodec.java
zipkin-java-core/src/test/java/io/zipkin/CodecTest.java
zipkin-java-server/src/main/java/io/zipkin/server/ZipkinQueryApiV1.java
zipkin-java-server/src/main/resources/zipkin-server.yml
zipkin-java-server/src/test/java/io/zipkin/server/ZipkinServerIntegrationTests.java

When a codec is reading, it is from a byte array, so the only possiblity
of problems is malformed input. This uses IllegalArgumentException to
indicate something the user can fix.
Since all domain objects are locally defined in core, and validated at
construction time, any errors writing to a byte array are bugs. This
uses AssertionError to indicate a bug.
Before, we weren't sending an error message to the user. This sends a
single-line description back in the 400 response. It also moves logging
to the call-site (`ZipkinQueryApiV1`).
Example curl request with bad content:
```bash
$ curl -X POST http://localhost:9411/api/v1/spans -H 'Content-Type: application/x-thrift' -d'foobar'
Malformed reading List<Span> from TBinary: Zm9vYmFy
```
Fixes #66

Removes null coersion in Codec in favor of IllegalArgumentException

---

interop/pom.xml
interop/src/test/java/zipkin/DependenciesTest.java
interop/src/test/java/zipkin/jdbc/JDBCDependenciesTest.java
interop/src/test/java/zipkin/server/InMemoryDependenciesTest.java
interop/src/test/java/zipkin/server/InMemoryScalaDependencyStoreTest.java
zipkin-server/src/main/java/zipkin/server/InMemorySpanStore.java
zipkin-spanstores/jdbc/src/main/java/zipkin/jdbc/DependencyLinkSpanIterator.java
zipkin-spanstores/jdbc/src/main/java/zipkin/jdbc/JDBCSpanStore.java
zipkin/src/main/java/zipkin/internal/DependencyLinkSpan.java
zipkin/src/main/java/zipkin/internal/DependencyLinker.java
zipkin/src/main/java/zipkin/internal/PeekingIterator.java
zipkin/src/test/java/zipkin/internal/PeekingIteratorTest.java

Previously, the in-memory provider did not support dependency
aggregation. This meant users couldn't play with zipkin unless they ran
MySQL. This adds aggregation support through a new type:
`DependencyLinksBuilder`.
This new type also corects the dependency graph, particularly around
uninstrumented services or paths with local spans intermediating calls.

Updates to latest zipkin-scala and adds in-mem dependency aggregation

---

pom.xml
zipkin-junit/README.md
zipkin-junit/pom.xml
zipkin-junit/src/main/java/zipkin/junit/ZipkinDispatcher.java
zipkin-junit/src/main/java/zipkin/junit/ZipkinRule.java
zipkin-junit/src/test/java/zipkin/junit/HttpSpanStore.java
zipkin-junit/src/test/java/zipkin/junit/ZipkinDispatcherTest.java
zipkin-junit/src/test/java/zipkin/junit/ZipkinRuleDependenciesTest.java
zipkin-junit/src/test/java/zipkin/junit/ZipkinRuleSpanStoreTest.java
zipkin-junit/src/test/java/zipkin/junit/ZipkinRuleTest.java
zipkin-server/src/main/java/zipkin/server/ZipkinQueryApiV1.java
zipkin-spanstores/jdbc/src/test/java/zipkin/jdbc/JDBCDependenciesTest.java
zipkin-spanstores/jdbc/src/test/java/zipkin/jdbc/JDBCSpanStoreTest.java
zipkin/src/main/java/zipkin/InMemorySpanStore.java
zipkin/src/main/java/zipkin/QueryRequest.java
zipkin/src/main/java/zipkin/internal/JsonCodec.java
zipkin/src/test/java/zipkin/DependenciesTest.java
zipkin/src/test/java/zipkin/InMemoryDependenciesTest.java
zipkin/src/test/java/zipkin/QueryRequestTest.java
zipkin/src/test/java/zipkin/SpanStoreTest.java
zipkin/src/test/java/zipkin/internal/JsonCodecTest.java

This adds ZipkinRule, a JUnit rule to spin-up a Zipkin server during tests. For example, you can write micro-integration tests like so:
```java
@Rule
public ZipkinRule zipkin = new ZipkinRule();
// Pretend we have a traced system under test
TracedService service = new TracedService(zipkin.httpUrl(), ReportingMode.FLUSH_EVERY);
@Test
public void skipsReportingWhenNotSampled() throws IOException {
zipkin.storeSpans(asList(rootSpan));
// send a request to the instrumented server, telling it not to sample.
client.addHeader("X-B3-TraceId", rootSpan.traceId)
.addHeader("X-B3-SpanId", rootSpan.id)
.addHeader("X-B3-Sampled", 0).get(service.httpUrl());
// check that zipkin didn't receive any new data in that trace
assertThat(zipkin.getTraces()).containsOnly(asList(rootSpan));
}
```
Fixes #64

Adds ZipkinRule

---

pom.xml
zipkin-junit/README.md
zipkin-junit/pom.xml
zipkin-junit/src/main/java/zipkin/junit/HttpFailure.java
zipkin-junit/src/main/java/zipkin/junit/ZipkinRule.java
zipkin-junit/src/test/java/zipkin/junit/ZipkinRuleTest.java
zipkin/pom.xml

For ZipkinRule to be effective in instrumentation tests, it needs to
inject failures. This adds failure patterns found in existing Brave and
spring-cloud-sleuth tests.

Adds HttpFailure and httpRequestCount to ZipkinRule

---

interop/pom.xml
interop/src/main/java/zipkin/interop/ScalaSpanStoreAdapter.java
pom.xml
zipkin/pom.xml
zipkin/src/main/java/zipkin/Span.java
zipkin/src/main/java/zipkin/internal/CorrectForClockSkew.java
zipkin/src/main/java/zipkin/internal/ThriftCodec.java
zipkin/src/test/java/zipkin/SpanStoreTest.java

This implements TBinaryProtocol directly in the ThriftCodec. By doing
the code, dependencies, and exceptions are simpler (as we are decoding
via a buffer not a network). This uses Okio Buffer, which also
simplified some code.
The payment was having to implement a couple utilities from libthrift,
namely the skip logic. Overall, the code is smaller and the binary
shrunk from 275k to 225k.

Removes internal use of libthrift

---

zipkin-junit/src/main/java/zipkin/junit/ZipkinDispatcher.java
zipkin-junit/src/test/java/zipkin/junit/ZipkinRuleTest.java
zipkin-server/pom.xml
zipkin-server/src/test/java/zipkin/server/ZipkinServerIntegrationTests.java

Adds a /health endpoint that returns actuator data or "OK" if the test server.
See https://github.com/openzipkin/zipkin/issues/997

Supports /heath endpoint

---

zipkin-junit/src/main/java/zipkin/junit/ZipkinDispatcher.java
zipkin-junit/src/test/java/zipkin/junit/ZipkinRuleTest.java
zipkin-server/src/main/java/zipkin/server/ZipkinQueryApiV1.java
zipkin-server/src/test/java/zipkin/server/ZipkinServerIntegrationTests.java
zipkin/src/main/java/zipkin/internal/Util.java
zipkin/src/test/java/zipkin/internal/UtilTest.java

This supports spans posted with "Content-Encoding: gzip".
Some of this code can be removed when Spring Boot supports request
decompression. Currently, compression is limited to responses only.
Fixes #69

Accepts gzip-encoded spans in zipkin-server and ZipkinRule

---

zipkin/src/main/java/zipkin/DependencyLink.java
zipkin/src/main/java/zipkin/internal/Dependencies.java
zipkin/src/main/java/zipkin/internal/ThriftCodec.java
zipkin/src/test/java/zipkin/internal/DependenciesTest.java

This adds thrift read methods that accept ByteBuffers. This is in
support of the underlying DataStax Cassandra driver, which returns data
in ByteBuffers. The implementation takes care not to re-buffer input
data.
This also introduces an internal type, Dependencies, which is only used
in cassandra: https://github.com/openzipkin/zipkin/issues/1008
See #89

Adds codec methods needed for Cassandra compatibility

---

zipkin-junit/src/main/java/zipkin/junit/ZipkinRule.java
zipkin-junit/src/test/java/zipkin/junit/ZipkinRuleTest.java
zipkin-server/src/main/resources/zipkin-server.yml

We were missing a parameter that controls GET compression. With this
change, json responses will be compressed.
Note: In spring-boot, only responses over a threshold are gzipped:
`server.compression.min-response-size` defaults to 2KiB.

Compresses GET responses

---

zipkin-junit/README.md
zipkin-junit/src/main/java/zipkin/junit/ZipkinRule.java
zipkin-junit/src/test/java/zipkin/junit/ZipkinRuleTest.java
zipkin/src/main/java/zipkin/InMemorySpanStore.java

This adds ZipkinRule.receivedSpanCount and ZipkinRule.receivedSpanBytes
to help instrumentation projects tune the amount of data they report.
Using this, instrumentation projects can verify they are sending less
bytes, ex via compression or less data duplication. They can also verify
they aren't sending more spans they expect. For example, instrumentation
can easily bundle the same span multiple times in the same POST request.

Adds ZipkinRule.receivedSpanCount and ZipkinRule.receivedSpanBytes

---

.gitignore
.travis.yml
README.md
interop/pom.xml
interop/src/test/java/zipkin/cassandra/CassandraScalaDependencyStoreTest.java
interop/src/test/java/zipkin/cassandra/CassandraScalaSpanStoreTest.java
interop/src/test/java/zipkin/cassandra/CassandraTestGraph.java
pom.xml
zipkin-server/README.md
zipkin-server/pom.xml
zipkin-server/src/main/java/zipkin/server/ZipkinCassandraProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java
zipkin-server/src/main/java/zipkin/server/brave/JDBCTracerConfiguration.java
zipkin-server/src/main/resources/zipkin-server.yml
zipkin-spanstores/cassandra/README.md
zipkin-spanstores/cassandra/pom.xml
zipkin-spanstores/cassandra/src/main/java/zipkin/cassandra/CassandraConfig.java
zipkin-spanstores/cassandra/src/main/java/zipkin/cassandra/CassandraSpanConsumer.java
zipkin-spanstores/cassandra/src/main/java/zipkin/cassandra/CassandraSpanStore.java
zipkin-spanstores/cassandra/src/main/java/zipkin/cassandra/CassandraUtil.java
zipkin-spanstores/cassandra/src/test/java/zipkin/cassandra/CassandraConfigTest.java
zipkin-spanstores/cassandra/src/test/java/zipkin/cassandra/CassandraDependenciesTest.java
zipkin-spanstores/cassandra/src/test/java/zipkin/cassandra/CassandraSpanStoreTest.java
zipkin-spanstores/cassandra/src/test/java/zipkin/cassandra/CassandraTestGraph.java
zipkin-spanstores/pom.xml

This is a port of `CassandraSpanStore` from zipkin-scala, except notably
not including the "slice query" infrastructure.
Note: While `CassandraSpanStore.accept` doesn't return a `Future`, it is
still asynchronous inside.
`zipkin-server` has been extended to optionally support Cassandra using
the same environment variables as zipkin-scala. For example, you can
start a process using cassandra as simply as setting the `STORAGE_TYPE`:
```bash
STORAGE_TYPE=cassandra ./mvnw -pl zipkin-server spring-boot:run
```
This uses the `Repository` class from `zipkin-cassandra-core`, which
internally uses DataStax Java Driver 2.1. It is likely that we'll
refactor out this dependency, for a couple reasons. One is that DataStax
Java Driver 3 is current. Another is that `Repository` was designed for
"slice …

Adds CassandraSpanStore including zipkin-server support

---

interop/src/main/java/zipkin/interop/ScalaSpanStoreAdapter.java
zipkin-junit/src/main/java/zipkin/junit/ZipkinDispatcher.java
zipkin-junit/src/main/java/zipkin/junit/ZipkinRule.java
zipkin-junit/src/test/java/zipkin/junit/HttpSpanStore.java
zipkin-server/src/main/java/zipkin/server/ZipkinQueryApiV1.java
zipkin-server/src/main/java/zipkin/server/ZipkinSpanWriter.java
zipkin-server/src/main/java/zipkin/server/brave/SpanStoreSpanCollector.java
zipkin-server/src/main/java/zipkin/server/brave/TraceWritesSpanStore.java
zipkin-spanstores/cassandra/src/main/java/zipkin/cassandra/CassandraSpanConsumer.java
zipkin-spanstores/cassandra/src/main/java/zipkin/cassandra/CassandraSpanStore.java
zipkin-spanstores/cassandra/src/test/java/zipkin/cassandra/CassandraDependenciesTest.java
zipkin-spanstores/jdbc/src/main/java/zipkin/jdbc/JDBCSpanStore.java
zipkin-spanstores/jdbc/src/test/java/zipkin/jdbc/JDBCDependenciesTest.java
zipkin/src/main/java/zipkin/InMemorySpanStore.java
zipkin/src/main/java/zipkin/SamplingSpanStoreConsumer.java
zipkin/src/main/java/zipkin/SpanConsumer.java
zipkin/src/main/java/zipkin/SpanStore.java
zipkin/src/test/java/zipkin/InMemoryDependenciesTest.java
zipkin/src/test/java/zipkin/SamplingSpanStoreConsumerTest.java
zipkin/src/test/java/zipkin/SpanStoreTest.java

Before this change, we accepted Iterator of spans instead of a list,
mainly to accomodate the sampling use case. It turns out that this is
awkward, and it also interferes with being able to know the count of
the input. Finally, in most cases the call to accept spans comes from
a codec, and that codec has already decoded a List. This changes the
primary input to a List instead of an Iterator.
This also moves the code that stores spans received by a transport into
a type `SpanConsumer`. This helps reduce the coupling around facets such
as collection-tier sampling, and also makes it easier to write other
transports such as Kafka.

Adds SpanConsumer and settles on List, not Iterator

---

pom.xml
zipkin-server/README.md
zipkin-server/pom.xml
zipkin-server/src/main/java/zipkin/server/ZipkinKafkaProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java
zipkin-server/src/main/resources/zipkin-server.yml
zipkin-transports/kafka/README.md
zipkin-transports/kafka/pom.xml
zipkin-transports/kafka/src/main/java/zipkin/kafka/KafkaConfig.java
zipkin-transports/kafka/src/main/java/zipkin/kafka/KafkaStreamProcessor.java
zipkin-transports/kafka/src/main/java/zipkin/kafka/KafkaTransport.java
zipkin-transports/kafka/src/main/java/zipkin/kafka/SpansDecoder.java
zipkin-transports/kafka/src/test/java/zipkin/kafka/KafkaTransportTest.java
zipkin-transports/kafka/src/test/resources/log4j.properties
zipkin-transports/pom.xml

This adds a Kafka transport, which receives messages in the same way as
zipkin-scala, using the same environment variables.
Closes #70

Adds Kafka Transport

---

zipkin-spanstores/cassandra/src/main/java/zipkin/cassandra/CassandraConfig.java
zipkin-spanstores/cassandra/src/test/java/zipkin/cassandra/CassandraConfigTest.java

When changing loadbalancer policy, we didn't consider a scenario brought
up by @michaelsembwever:
DCAwareRoundRobinPolicy will by default prefer the first contact node's
datacenter. If that node happens to be in a remote datacenter, latency
will be high, and the `LatencyAwarePolicy` cannot correct it (since
local nodes will be filtered out.
The previous logic is better because eventhough `RoundRobinPolicy` can
select a remote datacenter, it also selects local ones: the
`LatencyAwarePolicy` will eventually correct to choose only the local
ones.
See https://github.com/openzipkin/zipkin-java/pull/92/files#r55933918

Reverts default Cassandra host policy to RoundRobin

---

interop/src/main/java/zipkin/interop/ScalaSpanStoreAdapter.java
zipkin-junit/src/main/java/zipkin/junit/ZipkinDispatcher.java
zipkin-junit/src/main/java/zipkin/junit/ZipkinRule.java
zipkin-junit/src/test/java/zipkin/junit/HttpSpanStore.java
zipkin-server/src/main/java/zipkin/server/ZipkinQueryApiV1.java
zipkin-server/src/main/java/zipkin/server/brave/TraceWritesSpanStore.java
zipkin-server/src/test/java/zipkin/server/brave/SpanStoreSpanCollectorTest.java
zipkin-spanstores/cassandra/src/main/java/zipkin/cassandra/CassandraSpanStore.java
zipkin-spanstores/jdbc/src/main/java/zipkin/jdbc/JDBCSpanStore.java
zipkin/src/main/java/zipkin/InMemorySpanStore.java
zipkin/src/main/java/zipkin/SpanStore.java
zipkin/src/test/java/zipkin/SpanStoreTest.java

In zipkin-scala, `SpanStore.getTracesByIds` served its "slice query"
implementation. Basically, the old infrastructure performed queries in
two steps: first, fetch ids. then, get traces by ID.
From an HTTP Api point of view, it is single-id `GET /api/v1/trace/id`.
Moreover, how or if to fan-out is an implemantation detail that varies
per storage layer.
This rips out `SpanStore.getTracesByIds` for `getTrace`, as it
simplifies the api, and the [raw query](https://github.com/openzipkin/zipkin/pull/1027) easier to implement.

Changes SpanStore.getTracesByIds to getTrace

---

zipkin-server/README.md
zipkin-transports/kafka/README.md
zipkin-transports/kafka/pom.xml

This excludes a couple dependencies that leak through consumers such as
zipkin-server. It also adds instructions for testing Kafka using Docker.
Fixes #99

Excludes eagerly bound logging dependencies from Kafka

---

zipkin-junit/src/main/java/zipkin/junit/ZipkinDispatcher.java
zipkin-junit/src/test/java/zipkin/junit/HttpSpanStore.java
zipkin-junit/src/test/java/zipkin/junit/ZipkinRuleTest.java
zipkin-server/src/main/java/zipkin/server/ZipkinQueryApiV1.java
zipkin-server/src/main/java/zipkin/server/brave/TraceWritesSpanStore.java
zipkin-server/src/test/java/zipkin/server/ZipkinServerIntegrationTests.java
zipkin-spanstores/cassandra/src/main/java/zipkin/cassandra/CassandraSpanStore.java
zipkin-spanstores/jdbc/src/main/java/zipkin/jdbc/JDBCSpanStore.java
zipkin/src/main/java/zipkin/InMemorySpanStore.java
zipkin/src/main/java/zipkin/SpanStore.java
zipkin/src/test/java/zipkin/SpanStoreTest.java

When troubleshooting instrumentation, we sometimes need to hop to the
database to see what the collector stored (which is closer to what the
instrumentation sent).
In some cases, we are hunting down "clock skew" problems, and sometimes
that's a red herring. Some times we are looking to see if applications
are sending the same span multiple times. The reason we have to go to
the database is we can't quite tell if query-time adjustment logic is
helping or hurting.
This introduces a new query flag "raw" to the get trace endpoint. When
specified, no query time adjustments are made after data is returned
from the backend.
See https://github.com/openzipkin/zipkin/pull/1027

Supports viewing raw traces via GET /api/v1/trace/:id?raw

---

zipkin-transports/kafka/README.md
zipkin-transports/kafka/src/main/java/zipkin/kafka/SpansDecoder.java
zipkin-transports/kafka/src/test/java/zipkin/kafka/KafkaTransportTest.java

By allowing JSON encoded span lists as Kafka message values, we enable
users to send the same payload as they can over the http transport. It
also allows a very easy debug story, such as sending test spans via CLI.
This implementation peeks at the first byte in the Kafka message, and
attempts to decode json, if it is a '[', or decimal 91. When using
TBinaryProtocol (thrift) encoding, we know that the first byte will be
the Type, which is decimal <=16, so there's no risk of clash.
See https://github.com/openzipkin/zipkin/pull/1052

Allows transport-kafka to consume JSON encoded spans

---

zipkin-server/README.md
zipkin-server/src/main/java/zipkin/server/ZipkinCassandraProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java
zipkin-server/src/main/resources/zipkin-server.yml
zipkin-spanstores/cassandra/src/main/java/zipkin/cassandra/CassandraConfig.java

Span and Index Time-to-lives were already configurable, but not via properties. This fixes that.
* `CASSANDRA_SPAN_TTL`: Time-to-live in seconds for span data. Defaults to 604800 (7 days)
* `CASSANDRA_INDEX_TTL`: Time-to-live in seconds for index data. Defaults to 259200 (3 days)
By adding the above, we remain compatible with the scala query and collector services.
See https://github.com/openzipkin/zipkin/pull/1055

Exposes CASSANDRA_SPAN_TTL and CASSANDRA_INDEX_TTL variables

---

zipkin-server/pom.xml
zipkin-server/src/it/minimal-dependencies/pom.xml
zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java

Before, zipkin-server accidentally had a hard dependency on JDBC and
Cassandra. This defers loading these classes until we know they are
there and the feature is enabled.
Fixes #102

Prunes compile dependencies of zipkin-server to zipkin-core and spring

---

zipkin-server/README.md
zipkin-server/pom.xml
zipkin-server/src/main/java/zipkin/server/EnableZipkinServer.java
zipkin-server/src/main/java/zipkin/server/ZipkinServerProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinUiConfiguration.java
zipkin-server/src/main/resources/zipkin-server.yml

This hosts the `zipkin-ui` static assets on zipkin-server as opposed to relying on an external process (zipkin-web)
By doing, so, this allows us the following:
* Single-jar deployment option
* Simplest deployment of in-memory storage has no external dependencies
* The opportunity to use the standard port 8080
* Since web assets are hosted locally, there's no port dodging anymore
Implementation note: this currently cherry-picks routes the client-side is
responsible for.

Hosts zipkin-ui static assets on zipkin-server

---

zipkin/src/main/java/zipkin/SpanStore.java
zipkin/src/main/java/zipkin/internal/DependencyLinker.java
zipkin/src/test/java/zipkin/internal/DependencyLinkSpanTest.java
zipkin/src/test/java/zipkin/internal/DependencyLinkerTest.java

Problems around dependencies come in two major forms.
* The storage layer, which build DependencyLinkSpans
* The DependencyLinker, which processes DependencyLinkSpans
Before, there wasn't an easy way to separate these problems:
DependenciesTest existed, but was invoked from the storage layer.
By backfilling DependencyLinker tests, problems related to dependency
links can be resolved closer to the code responsible for them.

Backfills missing unit tests for dependency linker

---

interop/pom.xml
interop/src/main/java/zipkin/interop/ScalaSpanStoreAdapter.java
zipkin/src/main/java/zipkin/Endpoint.java
zipkin/src/test/java/zipkin/DependenciesTest.java

This is the last set of interop tests to port, particularly around
the dependency link functionality.
Fixes #110

Ports all remaining interop tests from zipkin-scala 1.38 to java

---

zipkin-server/src/it/minimal-dependencies/pom.xml

Before, we had to remember to update the pom to keep the
minimal-dependencies test relevant. This tokenizes it, removing the
maintenance.

Removes version maintenance from zipkin-server integration tests

---

.travis.yml
README.md
interop/pom.xml
interop/src/test/java/zipkin/elasticsearch/ElasticsearchScalaDependencyStoreTest.java
interop/src/test/java/zipkin/elasticsearch/ElasticsearchScalaSpanStoreTest.java
interop/src/test/java/zipkin/elasticsearch/ElasticsearchTestGraph.java
pom.xml
zipkin-server/README.md
zipkin-server/pom.xml
zipkin-server/src/main/java/zipkin/server/ZipkinElasticsearchProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java
zipkin-server/src/main/java/zipkin/server/ZipkinServerProperties.java
zipkin-server/src/main/resources/zipkin-server.yml
zipkin-spanstores/elasticsearch/README.md
zipkin-spanstores/elasticsearch/pom.xml
zipkin-spanstores/elasticsearch/src/main/java/zipkin/elasticsearch/ElasticsearchConfig.java
zipkin-spanstores/elasticsearch/src/main/java/zipkin/elasticsearch/ElasticsearchConstants.java
zipkin-spanstores/elasticsearch/src/main/java/zipkin/elasticsearch/ElasticsearchSpanConsumer.java
zipkin-spanstores/elasticsearch/src/main/java/zipkin/elasticsearch/ElasticsearchSpanStore.java
zipkin-spanstores/elasticsearch/src/main/java/zipkin/elasticsearch/IndexNameFormatter.java
zipkin-spanstores/elasticsearch/src/main/resources/zipkin/elasticsearch/zipkin_template.json
zipkin-spanstores/elasticsearch/src/test/java/zipkin/elasticsearch/ElasticsearchDependenciesTest.java
zipkin-spanstores/elasticsearch/src/test/java/zipkin/elasticsearch/ElasticsearchSpanStoreTest.java
zipkin-spanstores/elasticsearch/src/test/java/zipkin/elasticsearch/ElasticsearchTestGraph.java
zipkin-spanstores/elasticsearch/src/test/resources/logback.xml
zipkin-spanstores/pom.xml
zipkin/src/main/java/zipkin/Codec.java
zipkin/src/main/java/zipkin/internal/JsonCodec.java
zipkin/src/test/java/zipkin/DependenciesTest.java
zipkin/src/test/java/zipkin/SpanStoreTest.java

Also fixes a typo in SpanStoreTest that made it less stringent than the scala version.
Also fixes DependencyTest to use non-ordered assertions.
Also adds single DependencyLink serialization methods to JsonCodec.
Closes #103

Add an elasticsearch span store.

---

zipkin-server/pom.xml
zipkin-server/src/main/java/zipkin/server/ZipkinServerProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinUiConfiguration.java
zipkin-server/src/main/resources/zipkin-server.yml
zipkin-server/src/test/java/zipkin/server/ZipkinServerIntegrationTests.java

zipkin-ui includes some cache-related changes to make the experience
more responsive. It also introduces "Start time", which allows users
to control how far back to search for traces.
This includes a hard-coded cache policy, consistent with zipkin-scala.
* 1 minute for index.html
* 10 minute for /config.json
* 365 days for hashed resources (ex /app-e12b3bbb7e5a572f270d.min.js)
Since index.html links to hashed resource names, any change to it will
orphan old resources. That's why hashed resource age can be 365 days.
See #1062

Updates to zipkin-ui 1.39, notably addressing cache concerns

---

interop/pom.xml
zipkin-spanstores/cassandra/pom.xml
zipkin-transports/kafka/src/main/java/zipkin/kafka/KafkaStreamProcessor.java
zipkin-transports/kafka/src/main/java/zipkin/kafka/SpansDecoder.java
zipkin-transports/kafka/src/test/java/zipkin/kafka/KafkaTransportTest.java

While not documented, and possibly not intentional, `SpanStore.apply`
can throw. For example, we found that a span too large to store resulted
in an exception like below, which halted all further Kafka processing.
```
com.datastax.driver.core.exceptions.InvalidQueryException: Key length of 97122 is longer than maximum of 65535
```
This changes logic to skip and log error on any exception. To prevent
logs from filling up, the error message only includes ids.
This is a copy of https://github.com/openzipkin/zipkin/pull/1070

Prevents Kafka processing from halting on storage errors

---

interop/pom.xml
pom.xml
zipkin-spanstores/cassandra/src/main/java/zipkin/cassandra/CassandraSpanStore.java
zipkin-spanstores/guava/pom.xml

This sets a floor version of guava 18, which is bound by elasticsearch.
This will prevent us from accidentally using new signatures, causing errors like this:
```
com.google.common.util.concurrent.Futures.transformAsync(Lcom/google/common/util/concurrent/ListenableFuture;Lcom/google/common/util/concurrent/AsyncFunction;)Lcom/google/common/util/concurrent/ListenableFuture;] with root cause
```

Fixes guava version at 18 so as to avoid method not found errors

---

zipkin-server/src/main/java/zipkin/server/ZipkinMySQLProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java
zipkin-server/src/main/java/zipkin/server/brave/JDBCTracerConfiguration.java
zipkin-server/src/main/resources/zipkin-server.yml

Before, auto-configuration would initialize JDBC even when the storage
type was cassandra. This caused the health check to false negative.
One way attempted was to move the yaml config to inside zipkin as
opposed to spring. However, this still ended up being read by auto-
configuration. The end result was making this use the same properties
approach as other storage services, disabling auto-configuration in the
yaml file.
This helps us move towards better modularity #108 
Fixes #137

Makes JDBC initialization dependent on storage type

---

.gitignore
.travis.yml
pom.xml
zipkin-spanstores/elasticsearch/pom.xml
zipkin-transports/kafka/pom.xml
zipkin-transports/kafka/src/main/java/zipkin/kafka/KafkaTransport.java
zipkin-transports/kafka/src/test/java/zipkin/kafka/KafkaTestGraph.java
zipkin-transports/kafka/src/test/java/zipkin/kafka/KafkaTransportTest.java
zipkin-transports/kafka/src/test/resources/log4j.properties
zipkin-transports/kafka/src/test/resources/logback.xml

Kafka tests were failing on master. This does a few things to help:
* Starts ZK+Kafka in travis as opposed to via test lifecycle
* Don't exclude log4j: this is actually used by Kafka!
* Configure logback
* Don't try to use "localhost", which can fail. Use 127.0.0.1
* Close more resources
* Sets a hard timeout of 10 seconds to run all Kafka tests
* Ignores `skipsOnConsumerException` test for now, as breaks travis

Attempts to de-flake Kafka transport tests

---

zipkin-server/src/main/resources/zipkin-server.yml
zipkin/src/main/java/zipkin/internal/DependencyLinkSpan.java
zipkin/src/main/java/zipkin/internal/DependencyLinker.java
zipkin/src/test/java/zipkin/internal/DependencyLinkSpanTest.java

It can be vexing to troubleshoot why the dependency graph isn't working
out as expected. This adds log messages describing which spans were
involved in which links.

Adds debug logging for DependencyLinker

---

zipkin/src/test/java/zipkin/SpanStoreTest.java

ensures that https://github.com/openzipkin/zipkin/issues/1073 doesn't impact this codebase

Tests that empty binary annotation values don't crash

---

interop/src/test/java/zipkin/InMemoryScalaDependencyStoreTest.java
interop/src/test/java/zipkin/InMemoryScalaSpanStoreTest.java
interop/src/test/java/zipkin/cassandra/CassandraScalaDependencyStoreTest.java
interop/src/test/java/zipkin/elasticsearch/ElasticsearchScalaDependencyStoreTest.java
zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java
zipkin-server/src/main/java/zipkin/server/ZipkinUiConfiguration.java
zipkin-server/src/main/java/zipkin/server/ZipkinUiProperties.java
zipkin-server/src/test/java/zipkin/server/brave/SpanStoreSpanCollectorTest.java
zipkin/src/main/java/zipkin/InMemorySpanStore.java
zipkin/src/test/java/zipkin/InMemorySpanStoreTest.java
zipkin/src/test/java/zipkin/async/SamplingAsyncSpanConsumerTest.java

Particularly when using Spring, multiple inheritance can confuse things.
For example, if InMemorySpanStore implements AsyncSpanConsumer, and
another bean does, too, the user will have to explicitly choose which
they want. This complexity isn't helpful.
This unwinds `InMemorySpanStore` to only implement `SpanStore` directly.
In the near future, we will move to a component model which should
reduce this type of concern.
See #135

Unwinds inheritance of InMemorySpanStore

---

zipkin-server/src/main/java/zipkin/server/ZipkinHttpTransport.java
zipkin-transports/kafka/src/main/java/zipkin/kafka/KafkaStreamProcessor.java
zipkin-transports/kafka/src/main/java/zipkin/kafka/SpansDecoder.java
zipkin/src/main/java/zipkin/internal/SpanConsumerLogger.java
zipkin/src/test/java/zipkin/internal/SpanConsumerLoggerTest.java

Common logging patterns for span consumption lead to a consistent
troubleshooting experience, despite transport diversity.
Ex.
```bash
$ curl -X POST -s localhost:9411/api/v1/spans -d 'asdsadas'
Cannot decode spans due to IllegalArgumentException(Malformed reading List<Span> from json: asdsadas=)
```

Adds SpanConsumerLogger to make logging consistent across transports

---

pom.xml
zipkin-server/README.md
zipkin-server/pom.xml
zipkin-server/src/main/java/zipkin/server/ZipkinScribeProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java
zipkin-server/src/main/resources/zipkin-server.yml
zipkin-transports/kafka/src/main/java/zipkin/kafka/KafkaStreamProcessor.java
zipkin-transports/scribe/README.md
zipkin-transports/scribe/pom.xml
zipkin-transports/scribe/src/main/java/zipkin/scribe/Scribe.java
zipkin-transports/scribe/src/main/java/zipkin/scribe/ScribeConfig.java
zipkin-transports/scribe/src/main/java/zipkin/scribe/ScribeSpanConsumer.java
zipkin-transports/scribe/src/main/java/zipkin/scribe/ScribeTransport.java
zipkin-transports/scribe/src/test/java/zipkin/scribe/ScribeSpanConsumerTest.java

This re-adds the Scribe transport, formerly removed in #30. Scribe is
enabled by default in the exec jar (used in docker).
Custom builds can enable Scribe by including the `transport-scribe`
dependency. Further options may become available dependeding on the
outcome of our modularity discussion (#108).
This component honors the only relevant environment variable from
zipkin-scala: `ZIPKIN_COLLECTOR_PORT`. This sets the scribe listen port,
defaulting to port 9410.
Fixes #150

Re-adds Scribe transport

---

zipkin-transports/scribe/pom.xml

The Scribe transport's FB Swift (Thrift RPC) dependendency included
jsr303 which conflicts with Spring, causing the server to crash at
bootstrap. This was implicit via an unused implicit dependency,
airlift:configuration, which is now excluded.
Note this failure was only possible to see, if the exec jar was unpacked
and run via `java  -cp '.:lib/*' zipkin.server.ZipkinServer`.
Here's the exception encountered:
```
query_1 | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mysql.CONFIGURATION_PROPERTIES': Initialization of bean failed; nested exception is java.lang.AbstractMethodError: org.apache.bval.jsr303.ConfigurationImpl.getDefaultParameterNameProvider()Ljavax/validation/ParameterNameProvider;
query_1 | 	at …
```

Excludes airlift:configuration dependency to avoid classpath clash

---

benchmarks/README.md
benchmarks/pom.xml
benchmarks/src/main/java/zipkin/benchmarks/SpanBenchmarks.java
zipkin/src/main/java/zipkin/Endpoint.java
zipkin/src/main/java/zipkin/Span.java
zipkin/src/main/java/zipkin/internal/Util.java

I noticed another test was making my CPU fan go on. Turns out we are
needlessly doing work on sparse spans.
Here are the before and after from my laptop:
```
SpanBenchmarks.buildMinimalClientSpan  thrpt   15   7.440 ± 0.418  ops/us
SpanBenchmarks.buildMinimalSpan        thrpt   15  16.224 ± 1.089  ops/us
SpanBenchmarks.buildRPCSpan            thrpt   15   3.249 ± 0.270  ops/us
SpanBenchmarks.buildMinimalClientSpan  thrpt   15   12.384 ± 0.193  ops/us
SpanBenchmarks.buildMinimalSpan        thrpt   15  128.275 ± 1.363  ops/us
SpanBenchmarks.buildRPCSpan            thrpt   15    3.624 ± 0.209  ops/us
```

Makes empty spans cheaper to create

---

pom.xml
zipkin-samplers/pom.xml
zipkin-samplers/zookeeper/README.md
zipkin-samplers/zookeeper/pom.xml
zipkin-samplers/zookeeper/src/main/java/zipkin/sampler/zookeeper/ZooKeeperSampler.java
zipkin-samplers/zookeeper/src/test/java/zipkin/sampler/zookeeper/ZooKeeperSamplerTest.java
zipkin/src/main/java/zipkin/InternalSamplingAsyncSpanConsumer.java
zipkin/src/main/java/zipkin/Sampler.java
zipkin/src/main/java/zipkin/StorageComponent.java
zipkin/src/test/java/zipkin/SamplerTest.java

In practice, there are two purposes for sampler: instrumentation and
storage. This change allows a sampler to be used for both purposes.
It also makes the sampler extensible, so that the rate can be dynamic.
With this feature, it is possible to implement adaptive sampling via
ZooKeeper.
Part one of #164
Part two is rewriting out scala + twitter-util + flakey repository (likely with Curator)

Teaches Sampler to test spans and adds ZooKeeper support

---

zipkin-server/README.md
zipkin-server/pom.xml
zipkin-server/src/main/java/zipkin/server/brave/ApiTracerConfiguration.java
zipkin-server/src/main/java/zipkin/server/brave/BootstrapTrace.java
zipkin-server/src/main/java/zipkin/server/brave/BraveConfiguration.java
zipkin-server/src/main/java/zipkin/server/brave/JDBCTracerConfiguration.java
zipkin-server/src/main/java/zipkin/server/brave/SpanStoreSpanCollector.java
zipkin-server/src/main/resources/zipkin-server.yml
zipkin-server/src/test/java/zipkin/server/brave/SpanStoreSpanCollectorTest.java

This updates to latest Brave, and makes it possible to configure
self-tracing.
Self tracing exists to help troubleshoot performance of the zipkin-server.
When Brave dependencies are in the classpath, and `zipkin.self-tracing.enabled=true`,
Zipkin will self-trace calls to the api.
[yaml configuration](zipkin-server/src/main/resources/zipkin-server.yml) binds the following environment variables to spring properties:
Variable | Property | Description
--- | --- | ---
SELF_TRACING_ENABLED | zipkin.self-tracing.enabled | Set to false to disable self-tracing. Defaults to true
SELF_TRACING_FLUSH_INTERVAL | zipkin.self-tracing.flush-interval | Interval in seconds to flush self-tracing data to storage. Defaults to 1

Updates to Brave 3.6 and makes self-tracing optional

---

zipkin-server/README.md
zipkin-server/src/main/java/zipkin/server/EnableZipkinServer.java
zipkin-server/src/main/java/zipkin/server/ZipkinHttpCollector.java
zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java
zipkin-transports/kafka/README.md
zipkin-transports/kafka/src/main/java/zipkin/kafka/KafkaCollector.java
zipkin-transports/kafka/src/test/java/zipkin/kafka/KafkaCollectorTest.java
zipkin-transports/scribe/README.md
zipkin-transports/scribe/src/main/java/zipkin/scribe/ScribeCollector.java

This renames the server side of a transport collector.
Ex. KafkaTransport -> KafkaCollector
This maintains the name "transport" in artifacts, as they might include
a reporter one day, and the documentation are valid for both sides.
See https://github.com/openzipkin/openzipkin.github.io/issues/23

Names server side of a transport collector

---

zipkin-samplers/zookeeper/README.md
zipkin-samplers/zookeeper/pom.xml
zipkin-samplers/zookeeper/src/main/java/zipkin/sampler/zookeeper/SampleRateCalculator.java
zipkin-samplers/zookeeper/src/main/java/zipkin/sampler/zookeeper/SampleRateCalculatorInput.java
zipkin-samplers/zookeeper/src/main/java/zipkin/sampler/zookeeper/SampleRateListener.java
zipkin-samplers/zookeeper/src/main/java/zipkin/sampler/zookeeper/SampleRateUpdateGuard.java
zipkin-samplers/zookeeper/src/main/java/zipkin/sampler/zookeeper/SampleRateUpdater.java
zipkin-samplers/zookeeper/src/main/java/zipkin/sampler/zookeeper/ZooKeeperSampler.java
zipkin-samplers/zookeeper/src/test/java/zipkin/sampler/zookeeper/SampleRateCalculatorInputTest.java
zipkin-samplers/zookeeper/src/test/java/zipkin/sampler/zookeeper/SampleRateCalculatorTest.java
zipkin-samplers/zookeeper/src/test/java/zipkin/sampler/zookeeper/SampleRateListenerTest.java
zipkin-samplers/zookeeper/src/test/java/zipkin/sampler/zookeeper/SampleRateUpdateGuardTest.java
zipkin-samplers/zookeeper/src/test/java/zipkin/sampler/zookeeper/SampleRateUpdaterTest.java
zipkin-samplers/zookeeper/src/test/java/zipkin/sampler/zookeeper/ZooKeeperRule.java
zipkin-samplers/zookeeper/src/test/java/zipkin/sampler/zookeeper/ZooKeeperSamplerTest.java
zipkin-samplers/zookeeper/src/test/resources/log4j.properties
zipkin-samplers/zookeeper/src/test/resources/logback.xml

This implements the adaptive sampler in Java using Apache Curator. The
expected result is the same functionality with fewer build and runtime
dependencies.
Example:
```java
// The ZooKeeperSampler requires you to supply your own Curator.
client = CuratorFrameworkFactory.builder()
.connectString(zookeeperConnect)
.retryPolicy(new RetryOneTime(1))
.build();
client.start();
client.blockUntilConnected(3, TimeUnit.SECONDS);
// This will sample spans based on the capacity of the storage layer.
// Capacity is spans/minute and set by an admin.
sampler = new ZooKeeperSampler.Builder()
.id("kafka-" + topic + "@" + hostAndPort)
.build(client);
// Initialize a collector that will sample incoming spans based on
// a coordinated rate.
collector = new KafkaCollector.Builder() …
```

Rewrites ZooKeeperSampler to eliminate Scala dependency

---

benchmarks/src/main/java/zipkin/benchmarks/SpanBenchmarks.java
zipkin-storage/elasticsearch/src/main/java/zipkin/elasticsearch/ElasticsearchSpanStore.java
zipkin/src/main/java/zipkin/BinaryAnnotation.java
zipkin/src/main/java/zipkin/Span.java
zipkin/src/main/java/zipkin/internal/Util.java
zipkin/src/test/java/zipkin/SpanStoreTest.java
zipkin/src/test/java/zipkin/SpanTest.java

This adds `ElasticsearchSpanStore.MAX_RAW_SPANS`, which controls the maximum
raw spans returned by any trace query, regardless of trace count.
This is similar to `CassandraStorage.maxTraceCols`, which might warrant
renaming.
Fixes #159

Adds ElasticsearchSpanStore.MAX_RAW_SPANS to permit large query results

---

README.md
zipkin-junit/src/test/java/zipkin/junit/ZipkinDispatcherTest.java
zipkin-server/src/main/java/zipkin/server/ZipkinQueryApiV1.java
zipkin-storage/cassandra/src/test/java/zipkin/cassandra/CassandraDependenciesTest.java
zipkin-storage/elasticsearch/src/test/java/zipkin/elasticsearch/ElasticsearchDependenciesTest.java
zipkin/src/main/java/zipkin/Endpoint.java
zipkin/src/test/java/zipkin/DependenciesTest.java
zipkin/src/test/java/zipkin/InternalBlockingToAsyncSpanStoreAdapterTest.java
zipkin/src/test/java/zipkin/SpanTest.java
zipkin/src/test/java/zipkin/TestObjects.java

Names like "zipkin-web" and "zipkin-query" no longer exist

Makes examples use service names that exist in this repository

---

benchmarks/pom.xml
benchmarks/src/main/java/zipkin/benchmarks/CodecBenchmarks.java
benchmarks/src/main/java/zipkin/benchmarks/SpanBenchmarks.java
benchmarks/src/main/resources/span-client.json
benchmarks/src/main/resources/span-local.json
benchmarks/src/main/resources/span-rpc.json
pom.xml
zipkin/pom.xml
zipkin/src/main/java/zipkin/internal/JsonCodec.java
zipkin/src/main/java/zipkin/internal/ThriftCodec.java
zipkin/src/main/java/zipkin/internal/Util.java

This adds benchmarks around codecs, mainly to ensure the bundled
`zipkin.Codec` is competitive.
Here are the results from my macbook
```
Benchmark                                      Mode  Cnt     Score    Error   Units
CodecBenchmarks.readClientSpan_json_java      thrpt   15   100.003 ±  2.292  ops/ms
CodecBenchmarks.readClientSpan_json_scala     thrpt   15   134.154 ±  3.692  ops/ms
CodecBenchmarks.readClientSpan_thrift_java    thrpt   15   525.387 ± 20.644  ops/ms
CodecBenchmarks.readClientSpan_thrift_scala   thrpt   15   512.669 ± 16.775  ops/ms
CodecBenchmarks.readLocalSpan_json_java       thrpt   15   164.572 ±  1.836  ops/ms
CodecBenchmarks.readLocalSpan_json_scala      thrpt   15   208.522 ±  6.956  ops/ms
CodecBenchmarks.readLocalSpan_thrift_java     thrpt   15   915.019 ± …
```

Tweaks codec performance and adds benchmarks

---

zipkin/src/main/java/zipkin/CountingTraceIdSampler.java
zipkin/src/test/java/zipkin/TraceIdSamplerTest.java

This doubles the performance and increases the precision of the counting
trace ID sampler by using a bitset. After this, both the boundary and
counting sampler support a precision of 0.0001, or 0.01% sample rate.

Doubles performance of CountingTraceIdSampler while increasing precision

---

zipkin/src/main/java/zipkin/CountingTraceIdSampler.java
zipkin/src/test/java/zipkin/TraceIdSamplerTest.java

Previously, the counting sampler biased the first trace ids. For
example, if you had a sample rate of 50%, 5K traces would be sampled,
then 5K would not be. This would result in a poor experience for low
traffic sites. This randomizes the decisions, so that they are more
fair, and restores the granularity to 100 decisions.

Makes the counting sampler accurate to 100 decisions and more fair

---

zipkin-storage/cassandra/pom.xml
zipkin-storage/cassandra/src/main/java/zipkin/cassandra/internal/Repository.java
zipkin-storage/cassandra/src/main/java/zipkin/cassandra/internal/ZipkinRetryPolicy.java
zipkin-storage/cassandra/src/test/java/zipkin/cassandra/ClusterProviderTest.java

By updating to Datastax Driver 3, we still support Cassandra 2.2+, but
also 3.0.
Tested against Cassandra 2.2, 3.0 and 3.5
Fixes #183

Updates to Datastax Cassandra Driver 3.0

---

zipkin-server/README.md
zipkin-server/src/main/java/zipkin/server/ZipkinKafkaProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java
zipkin-server/src/main/resources/zipkin-server.yml
zipkin-transports/kafka/src/main/java/zipkin/kafka/KafkaCollector.java
zipkin-transports/kafka/src/test/java/zipkin/kafka/KafkaCollectorTest.java

Kafka requires global coordination of `message.max.bytes`. This impacts
collectors even if zipkin spans don't approach this amount. To configure
this, we add `KafkaCollector.Builder.maxMessageSize` and the environment
variable `KAFKA_MAX_MESSAGE_SIZE`.
Same as https://github.com/openzipkin/zipkin/pull/1109
See #184

Makes max message size configurable in Kafka

---

centralsync-maven-plugin/pom.xml
pom.xml
zipkin-junit/pom.xml
zipkin-samplers/zookeeper/pom.xml
zipkin-server/pom.xml
zipkin-storage/cassandra/pom.xml
zipkin-storage/elasticsearch/pom.xml
zipkin-storage/guava/pom.xml
zipkin-storage/jdbc/pom.xml
zipkin-transports/kafka/src/main/java/zipkin/kafka/KafkaCollector.java
zipkin-transports/scribe/pom.xml
zipkin/pom.xml

Before this change, it was hard to tell which module required JRE 8.
This makes it explicit, by defaulting src/main to Java 1.7

Makes explicit which modules require JRE 8

---

zipkin-server/src/main/java/zipkin/server/ZipkinUiProperties.java
zipkin-server/src/main/resources/zipkin-server.yml

The Zipkin browser extensions will talk to the Zipkin server and
ask it which sites it is supposed to receive traces from. E.g.
you could have multiple Zipkin installations, one for every
environment:
http://www.mysite.com instrumented by http://prod-zipkin.mysite.com
http://dev.mysite.com instrumented by http://dev-zipkin.mysite.com
http://ci.mysite.com instrumented by http://ci-zipkin.mysite.com
By setting the configuration "instrumented" (a regex expression)
we can help the browser extension dispatch trace URLs to the correct
Zipkin server backend.
E.g. for a Zipkin installation at http://dev-zipkin.mysite.com,
setting "instrumented" to ".*:\/\/dev\.mysite\.com\/.*" would mean
all requests accessing dev.mysite.com/* produce traces that
end up in http://dev-zipkin.mysite.com/traces/XXX. …

Add optional configuration: instrumented site(s)

---

zipkin-sampler/zookeeper/src/main/java/zipkin/sampler/zookeeper/ZooKeeperCollectorSampler.java
zipkin-server/src/main/java/zipkin/server/ConditionalOnSelfTracing.java
zipkin-server/src/main/java/zipkin/server/ZipkinCassandraProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinElasticsearchProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinHttpCollector.java
zipkin-server/src/main/java/zipkin/server/ZipkinKafkaProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinScribeProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java
zipkin-server/src/main/java/zipkin/server/brave/ApiTracerConfiguration.java
zipkin-server/src/main/java/zipkin/server/brave/BraveConfiguration.java
zipkin-server/src/main/java/zipkin/server/brave/CassandraTracerConfiguration.java
zipkin-server/src/main/java/zipkin/server/brave/JDBCTracerConfiguration.java
zipkin-storage/cassandra/src/main/java/zipkin/cassandra/CassandraStorage.java
zipkin-storage/cassandra/src/main/java/zipkin/cassandra/LazySession.java
zipkin-storage/cassandra/src/main/java/zipkin/cassandra/SessionFactory.java
zipkin-storage/cassandra/src/test/java/zipkin/cassandra/SessionFactoryTest.java
zipkin-storage/elasticsearch/src/main/java/zipkin/elasticsearch/ElasticsearchStorage.java
zipkin-storage/jdbc/src/main/java/zipkin/jdbc/JDBCStorage.java
zipkin-transports/kafka/src/main/java/zipkin/kafka/KafkaCollector.java
zipkin-transports/scribe/src/main/java/zipkin/scribe/ScribeCollector.java

ConditionalOnClass lookups have proven unreliable and extremely
difficult to unwind. For example, the behavior is inconsistent between
the JRE on alpine linux and on a macbook. Rather than continue losing
time on matters like these, this moves to a more explicit condition.

Fixes self-tracing auto-configuration by quitting ConditionalOnClass

---

interop/pom.xml
interop/src/test/java/zipkin/jdbc/JDBCTestGraph.java

There's a bug in Eclipse JDT which makes the interop project
uncompilable with Java 8
(https://bugs.eclipse.org/bugs/show_bug.cgi?id=468276). Since
only one small Java 8 feature was being used in one test
in the whole project, it seems like a small price to pay
to sacrifice that for being able to compile and run in the IDE.

Downgrade interop module to Java 7 to support Eclipse users

---

zipkin-storage/cassandra/src/main/java/zipkin/cassandra/CassandraSpanConsumer.java
zipkin-storage/cassandra/src/main/java/zipkin/cassandra/CassandraSpanStore.java
zipkin-storage/cassandra/src/main/java/zipkin/cassandra/CassandraStorage.java

There were a couple glitches in the async behavior of cassandra. First,
we were inconsistent on future collecting, and accidentally mapped
against failed futures. Less importantly, we forgot to chain one future
in the storage query.
This fixes those issues and documents the results.
Fixes #199

Cleans up async behavior in CassandaStorage

---

benchmarks/pom.xml
interop/pom.xml
interop/src/main/java/zipkin/interop/ScalaSpanStoreAdapter.java
zipkin-server/pom.xml
zipkin-storage/cassandra/src/main/java/zipkin/cassandra/CassandraSpanStore.java
zipkin-storage/elasticsearch/src/main/java/zipkin/elasticsearch/ElasticsearchSpanStore.java
zipkin-storage/jdbc/src/main/java/zipkin/jdbc/JDBCSpanStore.java
zipkin/src/main/java/zipkin/InMemorySpanStore.java
zipkin/src/test/java/zipkin/SpanStoreTest.java

This makes it possible to make cross-service tools without an explicit
fan-out. This is a port of https://github.com/openzipkin/zipkin/pull/1102
Fixes #182
cc @esbie

Makes /api/v1/traces serviceName parameter optional

---

zipkin-server/pom.xml
zipkin-server/src/main/java/zipkin/server/brave/TracedSession.java
zipkin-server/src/main/resources/zipkin-server.yml

This adds propagation to cassandra self-tracing. When the receiver has
zipkin instrumentation installed, zipkin self-traces will propagate and
include the underlying storage operations

Adds propagation to cassandra self-tracing

---

zipkin-storage/elasticsearch/src/main/java/zipkin/elasticsearch/ElasticsearchSpanStore.java
zipkin/src/main/java/zipkin/internal/DependencyLinkSpan.java
zipkin/src/main/java/zipkin/internal/JsonCodec.java
zipkin/src/main/java/zipkin/internal/SpanConsumerLogger.java
zipkin/src/main/java/zipkin/internal/Util.java
zipkin/src/test/java/zipkin/internal/UtilTest.java

Before, we were very slow at hex encoding, and this made the json
encoding notably slower than necessary. We were also inefficient by
using regex to check a hex string. This fixes both issues, notably
improving encoding performance.
```
CodecBenchmarks.readLocalSpan_json_java  thrpt   15  155.571 ± 10.273  ops/ms
CodecBenchmarks.writeLocalSpan_json_java  thrpt   15  131.598 ± 11.653  ops/ms
CodecBenchmarks.readLocalSpan_json_java  thrpt   15  162.043 ± 2.652  ops/ms
CodecBenchmarks.writeLocalSpan_json_java  thrpt   15  203.380 ± 6.892  ops/ms
```

Improves json codec performance by being more efficient with hex codec

---

zipkin-server/src/main/java/zipkin/server/ZipkinQueryApiV1.java
zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java
zipkin-server/src/main/java/zipkin/server/brave/ApiTracerConfiguration.java
zipkin-server/src/main/java/zipkin/server/brave/BraveConfiguration.java
zipkin-server/src/main/java/zipkin/server/brave/JDBCTracerConfiguration.java
zipkin-server/src/main/java/zipkin/server/brave/TracedAsyncSpanConsumer.java
zipkin-server/src/main/java/zipkin/server/brave/TracedSession.java
zipkin-server/src/main/java/zipkin/server/brave/TracedSpanStore.java
zipkin-server/src/main/java/zipkin/server/brave/TracedStorageComponent.java
zipkin-storage/cassandra/src/main/java/zipkin/cassandra/CassandraDependenciesWriter.java
zipkin-storage/cassandra/src/main/java/zipkin/cassandra/CassandraSpanConsumer.java
zipkin-storage/cassandra/src/main/java/zipkin/cassandra/CassandraSpanStore.java
zipkin-storage/cassandra/src/main/java/zipkin/cassandra/CassandraUtil.java
zipkin-storage/cassandra/src/main/java/zipkin/cassandra/NamedBoundStatement.java

This fixes a thread propagation issue in Cassandra self-tracing that
prevented us from seeing all the spans.
This also logs traces for the POST endpoint, so that we can compare
how different implementations perform and are implemented.
Here's comparisons of all the storage systems storing a 4-span trace. The graph is the result of the second POST, so as to avoid showing lag from first network connect etc.
mem:
mysql:
cassandra:
elasticsearch:
Notice that we've not yet instrumented elasticsearch, so we can't really tell how much work is going on.

Fixes Cassandra self-tracing and enables POST tracing

---

zipkin-server/README.md

By changing instructions to talk more about the jar than maven, this document aligns
more closely to docker etc which don't use maven at runtime.
Thanks to @shakuzen for the suggestion about log levels

Switches server to discuss the exec jar and adds log description

---

.travis.yml
travis/publish.sh

Since our release task makes tags, not branches, version commits end up
on master. These deploy, so we can't also build the tag, too.
This consolidates code around deployment to the master branch, and uses
the maven version to tell if it should be synchronized to maven central
or not.
Fixes #220
Partially reverts a4bf8e1c47eae314c44fac075c89797817c93876

Deploys snapshots and versions from master

---

interop/src/test/java/zipkin/storage/cassandra/CassandraTestGraph.java
interop/src/test/java/zipkin/storage/elasticsearch/ElasticsearchTestGraph.java
pom.xml
zipkin-collector/kafka/src/main/java/zipkin/collector/kafka/KafkaCollector.java
zipkin-collector/kafka/src/test/java/zipkin/collector/kafka/KafkaCollectorTest.java
zipkin-collector/scribe/src/main/java/zipkin/collector/scribe/ScribeCollector.java
zipkin-collector/scribe/src/test/java/zipkin/collector/scribe/ScribeCollectorTest.java
zipkin-collector/scribe/src/test/java/zipkin/collector/scribe/ScribeSpanConsumerTest.java
zipkin-junit/src/test/java/zipkin/junit/HttpStorage.java
zipkin-server/src/it/execjar/src/test/java/zipkin/execjar/DoesntCrashWhenKafkaZooKeeperIsDownTest.java
zipkin-server/src/main/java/zipkin/server/ZipkinHealthIndicator.java
zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java
zipkin-server/src/main/java/zipkin/server/brave/TracedSession.java
zipkin-server/src/main/java/zipkin/server/brave/TracedStorageComponent.java
zipkin-storage/cassandra/src/main/java/zipkin/storage/cassandra/CassandraStorage.java
zipkin-storage/cassandra/src/test/java/zipkin/storage/cassandra/CassandraStorageTest.java
zipkin-storage/cassandra/src/test/java/zipkin/storage/cassandra/CassandraTestGraph.java
zipkin-storage/elasticsearch/src/main/java/zipkin/storage/elasticsearch/ElasticsearchStorage.java
zipkin-storage/elasticsearch/src/test/java/zipkin/storage/elasticsearch/ElasticsearchStorageTest.java
zipkin-storage/elasticsearch/src/test/java/zipkin/storage/elasticsearch/ElasticsearchTestGraph.java
zipkin-storage/jdbc/pom.xml
zipkin-storage/jdbc/src/main/java/zipkin/storage/jdbc/JDBCStorage.java
zipkin-storage/jdbc/src/test/java/zipkin/storage/jdbc/JDBCStorageTest.java
zipkin/src/main/java/zipkin/Component.java
zipkin/src/main/java/zipkin/collector/CollectorComponent.java
zipkin/src/main/java/zipkin/storage/InMemoryStorage.java

This pulls out an interface: Component, which has the ability to report
its health via a `check()` method. This is ported to all storage and
collector components. Notably, this also fixes a crash when Kafka isn't
running when zipkin was started.
Fixes #140
Inspired by:
* https://github.com/Netflix/denominator/blob/master/core/src/main/java/denominator/CheckConnection.java
* https://github.com/dropwizard/metrics/blob/3.1-maintenance/metrics-healthchecks/src/main/java/com/codahale/metrics/health/HealthCheck.java

Extracts Component, which has a check() method for determining health

---

zipkin-server/src/main/java/zipkin/server/ZipkinQueryApiV1.java
zipkin-server/src/main/resources/zipkin-server.yml
zipkin-server/src/test/java/zipkin/server/ZipkinServerIntegrationTests.java

Same as https://github.com/openzipkin/zipkin/issues/718, except
including the span names endpoint (/api/v1/spans)
Defaults to 300 seconds, overridable via zipkin.query.names-max-age
Fixes #229

Adds cache headers to /api/v1/services and /api/v1/spans

---

zipkin-server/src/main/java/zipkin/server/ZipkinCassandraProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinElasticsearchProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinKafkaProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinMySQLProperties.java
zipkin-server/src/main/java/zipkin/server/ZipkinScribeProperties.java
zipkin-server/src/main/resources/zipkin-server.yml

Before, spring configuration keys for storage or collectors were top-
level. For example, `kafka.X` or `cassandra.Y`. This clutters up the
namespace and interferes with modularity. These properties are now
namespaced like `zipkin.collector.kafka.X` or
`zipkin.storage.cassandra.Y`.
See #108

Namespaces spring configuration to match package names

---

pom.xml
zipkin-server/pom.xml
zipkin-ui/pom.xml

Currently, users have to track 2 zipkin versions to function:
* 0.X - for the almost all of the code
* 1.X - for the UI
This double-maintenance is a reality for zipkin developers, until we
complete the transition to a single repository. However, we shouldn't
subject users to that, particularly as they don't know when they should
update the UI version (for example that version changes if unrelated
scala code is released).
By repackaging zipkin-ui here, we can hide this complexity from users,
and better prepare ourselves to transition to building the UI using
https://github.com/eirslett/frontend-maven-plugin

Hides zipkin-ui version complexity from end users

---

zipkin-autoconfigure/collector-kafka/src/main/java/zipkin/autoconfigure/collector/kafka/ZipkinKafkaCollectorProperties.java
zipkin-autoconfigure/collector-scribe/src/main/java/zipkin/autoconfigure/collector/scribe/ZipkinScribeCollectorProperties.java
zipkin-autoconfigure/storage-cassandra/src/main/java/zipkin/autoconfigure/storage/cassandra/ZipkinCassandraStorageProperties.java
zipkin-autoconfigure/storage-elasticsearch/src/main/java/zipkin/autoconfigure/storage/elasticsearch/ZipkinElasticsearchStorageProperties.java
zipkin-autoconfigure/storage-mysql/src/main/java/zipkin/autoconfigure/storage/mysql/ZipkinMySQLStorageProperties.java
zipkin-server/src/main/resources/zipkin-server.yml

Config property namespacing broke environment variable mapping.
This reverts that and also fixes a pom glitch in elasticsearch.

Revert "Namespaces spring configuration to match package names"

---

README.md

There was a long discussion in #198 that aimed to get around the fact that there's no single URL to fetch the latest version of an artifact from Bintray. One solution we didn't consider: fetch it from Maven Central, not Bintray. Problem solved, methinks.

Quick-start instructions. Fix #198

---

zipkin-storage/cassandra/src/main/java/zipkin/storage/cassandra/CassandraStorage.java
zipkin-storage/elasticsearch/src/main/java/zipkin/storage/elasticsearch/ElasticsearchStorage.java
zipkin-storage/mysql/src/main/java/zipkin/storage/mysql/MySQLStorage.java

When integrating with other tools or testing, it is helpful to reuse
the same connection as zipkin does.

Exposes the underlying client in use by the storage component

---

zipkin/src/main/java/zipkin/internal/Lazy.java
zipkin/src/main/java/zipkin/internal/LazyCloseable.java
zipkin/src/test/java/zipkin/internal/LazyCloseableTest.java

Exceptions computing I/O intensive values can harm the process or the
backend. This teaches LazyCloseable to remember exceptions for a bit to
reduce that damage. The value is hard-set to 1 second which allows us
to mitigate the issue without adding a configuration burden.
Fixes #248

Teaches LazyCloseable to remember exceptions for a bit

---

zipkin-storage/cassandra/README.md
zipkin-storage/elasticsearch/README.md
zipkin-storage/mysql/README.md

Some time back, we made sure developers aren't required to install and
run all data stores as a prerequisite of developing Zipkin. What we did
was made each of these conditional on environment, and skip integration
tests otherwise. We setup Travis such that all datastores are available,
so that no tests are skipped during pull requests.
What we didn't do was document what was going on, and this led to
confusion from different people who were curious about why pull requests
fail while local tests pass, or if integration tests run at all.

Adds docs on how storage tests run

---

zipkin-ui/pom.xml
zipkin/src/main/java/zipkin/storage/QueryRequest.java
zipkin/src/test/java/zipkin/storage/QueryRequestTest.java

This updates to the latest zipkin javascript, which includes the JSON button and error reporting. This fixes a validation bug found when trying it out!
Thanks to @virtuald for the javascript work involved and @eirslett for all the code reviews.

Updates to the latest zipkin-ui javascript and fixes validation bug

---

zipkin-autoconfigure/storage-cassandra/src/main/java/zipkin/autoconfigure/storage/cassandra/ZipkinCassandraStorageProperties.java
zipkin-server/README.md
zipkin-storage/cassandra/src/main/java/zipkin/storage/cassandra/CassandraSpanConsumer.java
zipkin-storage/cassandra/src/main/java/zipkin/storage/cassandra/CassandraSpanStore.java
zipkin-storage/cassandra/src/main/java/zipkin/storage/cassandra/CassandraStorage.java
zipkin-storage/cassandra/src/main/java/zipkin/storage/cassandra/Schema.java
zipkin-storage/cassandra/src/main/resources/cassandra-schema-cql3-upgrade-1.txt
zipkin-storage/cassandra/src/test/java/zipkin/storage/cassandra/CassandraDependenciesTest.java
zipkin-storage/cassandra/src/test/java/zipkin/storage/cassandra/CassandraWithOriginalSchemaSpanStoreTest.java
zipkin-storage/cassandra/src/test/java/zipkin/storage/cassandra/CassandraWithOriginalSchemaTestGraph.java
zipkin-storage/cassandra/src/test/resources/cassandra-schema-cql3-original.txt

Improvements to the Cassandra storage
- the schema now defines default TTL for each table
- deprecates manually controlling span and index ttl
- supports upgrading the schema
See #240

Updates Cassandra schema to include default ttls and adds upgrade logic
