openzipkin/zipkin-java

README.md, docker-compose.yml, pom.xml, zipkin-java-query/src/main/java/io/zipkin/query/InMemoryZipkinQuery.java, zipkin-java-query/src/test/java/io/zipkin/query/ZipkinQueryTest.java, zipkin-java-server/Dockerfile
cc @dsyer @spencergibb @abesto
=> Adds docker-compose instructions

zipkin-java-core/src/main/java/io/zipkin/Annotation.java, zipkin-java-core/src/main/java/io/zipkin/BinaryAnnotation.java, zipkin-java-core/src/main/java/io/zipkin/Constants.java, zipkin-java-core/src/main/java/io/zipkin/Endpoint.java, zipkin-java-scribe/src/test/java/io/zipkin/scribe/ScribeSpanConsumerTest.java
=> Updates docs around endpoint and adds scribe parse test

pom.xml, swift-codec/pom.xml, zipkin-java-core/pom.xml, zipkin-java-dependencies/pom.xml, zipkin-java-query/pom.xml, zipkin-java-scribe/pom.xml, zipkin-java-server/dependency-reduced-pom.xml, zipkin-java-server/pom.xml
Configure project to support publishing of
snapshots and release artefacts according to
instructions found here:
http://central.sonatype.org/pages/apache-maven.html
=> Enable artefact publishing configuration

zipkin-java-core/src/main/java/io/zipkin/Constants.java, zipkin-java-core/src/main/java/io/zipkin/Span.java, zipkin-java-query/pom.xml, zipkin-java-query/src/main/java/io/zipkin/query/InMemoryZipkinQuery.java, zipkin-java-query/src/main/java/io/zipkin/query/QueryRequest.java, zipkin-java-query/src/test/java/io/zipkin/query/InMemoryZipkinQuerySpanStoreTest.java, zipkin-java-query/src/test/java/io/zipkin/query/InMemoryZipkinQueryTest.java, zipkin-java-query/src/test/java/io/zipkin/query/ZipkinQuerySpanStoreAdapter.java, zipkin-java-query/src/test/java/io/zipkin/query/ZipkinQueryTest.java, zipkin-java-scribe/src/main/java/io/zipkin/scribe/ScribeSpanConsumer.java
Running the same tests as the scala side of OpenZipkin should help increase confidence in the java port.
=> Adds integration tests from scala project and addresses drift

zipkin-java-server/pom.xml
The main problem     is that there is a clash between 2 impls
of jsr-303. One of them has to be exlcuded.
=> Trim dependencies a bit

zipkin-java-server/pom.xml, zipkin-java-server/src/main/java/com/github/kristofa/brave/ApiTracerConfiguration.java, zipkin-java-server/src/main/java/com/github/kristofa/brave/MySqlTracerConfiguration.java, zipkin-java-server/src/main/java/io/zipkin/server/EnableZipkinServer.java, zipkin-java-server/src/main/java/io/zipkin/server/brave/ApiTracerConfiguration.java, zipkin-java-server/src/main/java/io/zipkin/server/brave/MySqlTracerConfiguration.java, zipkin-java-server/src/main/resources/zipkin-server.yml
Add support for MySQL tracing (broken because of cycle)
Move static beans into private local methods
=> Refactor to avoid using package private stuff in Brave

docker-compose.yml, zipkin-java-server/Dockerfile, zipkin-java-server/src/main/java/io/zipkin/server/ZipkinServerConfiguration.java, zipkin-java-server/src/main/java/io/zipkin/server/ZipkinServerProperties.java, zipkin-java-server/src/main/resources/zipkin-server.yml
Makes the docker side of the business just like the others
=> Tidies up docker configuration with upstream

.settings.xml, .travis.yml
* publish to sonatype if merge is not a PR
* added the gpg block in case we need it.  For some reason I left passphrase out and it still worked O_o.  Checking in keys also seemed some what janky.  Please let me know if you have an opinion on this.
(might be the maven-gpg-plugin thats installed)
* openzipkin-release (openzipkin@gmail.com) user
* need to do a test when code is merged into master
* TRAVIS_BRANCH - is the branch you are merging into, which almost always is master.  TRAVIS_PULL_REQUEST - is either false or the PR number.  This makes the assumption that if you are on master and it is not a pull request, then the result is something to snapshot.
=> Add snapshot publishing

zipkin-java-server/src/main/java/io/zipkin/server/brave/JDBCTracerConfiguration.java
This is a temporary fix to properly annotate the server our JDBC code
queries.
See https://github.com/openzipkin/brave/issues/104
=> Attaches the remote JDBC address as a zipkin "sa" annotation

zipkin-java-server/pom.xml
This change does not compromise functionality but it speeds up
start up (shaves approx. 1s off 4s startup time on my laptop).
=> Switch to Tomcat data source in place of Hikari

zipkin-java-server/pom.xml, zipkin-java-server/src/main/java/io/zipkin/server/ZipkinServerConfiguration.java, zipkin-java-server/src/main/java/io/zipkin/server/brave/ApiTracerConfiguration.java, zipkin-java-server/src/main/java/io/zipkin/server/brave/BraveConfiguration.java
Brave is an extra dependency, and some people might prefer not
to use it. The change to make it optional is fairly trivial
so it seems worth it.
=> Make brave optional

zipkin-spanstores/jdbc/src/main/java/zipkin/jdbc/JDBCSpanStore.java, zipkin/src/main/java/zipkin/internal/ApplyTimestampAndDuration.java, zipkin/src/test/java/zipkin/SpanStoreTest.java
This ports remaining tests to java, and also ports code changes needed
to make them pass.
=> Ports remaining scala SpanStoreSpec tests to SpanStoreTest

zipkin-server/src/main/java/zipkin/server/ZipkinUiConfiguration.java
Before, png resources had an invalid header:
`Content-Type: image/png;charset=UTF-8`
See #116
See https://github.com/spring-projects/spring-boot/issues/5459
=> Opts out of adding character set to png resources

zipkin-spanstores/cassandra/src/main/java/zipkin/cassandra/CassandraUtil.java
Uses a thread local to avoid state conflicts.
Fixes #125
=> Fixes unsafe use of CharsetEncoder

zipkin/src/main/java/zipkin/InMemorySpanStore.java, zipkin/src/test/java/zipkin/DependenciesTest.java
Also backfills test to ensure everything else works
Problem and fix by @marcingrzejszczak
Fixes #144
=> Merges spans before linking dependencies in InMemorySpanStore

zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java
`@ConditionalOnClass` has been unreliable in docker, regardless of
whether we unpack the all-jar or not. For example, mysql currently fails
in docker eventhough all of its classes are in the classpath, while
Cassandra works.
We already have a test to ensure optional dependencies are optional,
and we already have a property that is only set when someone wants a
specific storage component (`zipkin.storage.type`). The extra class
checking is unnecessary complexity, so let's not do it.
=> Simplifies wiring to not attempt to detect classes

zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java
There was a subtle wiring mistake, which manual testing found. Basically,
if we declare DataSource as a bean, it can interfere with
auto-configuration.
=> Makes DataSource really overridable

interop/pom.xml, zipkin-server/pom.xml, zipkin-storage/cassandra/pom.xml
This grabs a cassandra dependency update
=> Updates to latest zipkin-scala

zipkin-server/README.md
This highlights that zipkin-server is a Spring Boot application, as that
clarifies which admin endpoints are available. It also makes explicit
that environment variables are actually bound to yaml configuration.
=> Clarifies zipkin-server's endpoints and how configuration works

zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java, zipkin-server/src/main/java/zipkin/server/brave/ApiTracerConfiguration.java, zipkin-server/src/main/java/zipkin/server/brave/BraveConfiguration.java, zipkin-server/src/main/java/zipkin/server/brave/TracedSession.java, zipkin-storage/cassandra/src/main/java/zipkin/cassandra/CassandraSpanConsumer.java, zipkin-storage/cassandra/src/main/java/zipkin/cassandra/CassandraStorage.java, zipkin-storage/cassandra/src/main/java/zipkin/cassandra/LazySession.java, zipkin-storage/cassandra/src/main/java/zipkin/cassandra/Schema.java, zipkin-storage/cassandra/src/main/java/zipkin/cassandra/SessionProvider.java, zipkin-storage/cassandra/src/test/java/zipkin/cassandra/SessionProviderTest.java
This adds client-side self-tracing, propagation penciled in for later.
=> Adds cassandra client-side self-tracing

zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java
=> Simplifies Kafka condition and fixes flakiness

zipkin-storage/cassandra/src/main/java/zipkin/cassandra/CassandraSpanStore.java
While `GET /api/v1/traces` without `serviceName` won't work, and
probably other features will also break 2.1, this adds a workaround
which should buy Cassandra 2.1 users a little more time to upgrade.
See https://groups.google.com/forum/#!forum/zipkin-user
Fixes #208
=> Buys Cassandra 2.1 users a little more time to upgrade

.settings.xml, .travis.yml, travis/publish.sh
@adriancole What do you think? I didn't do a full integration test, but many of the individual pieces seem to work.
(Aborted the Travis runs to not mess up anything before a review is done)
=> First attempt to implement release via Travis CI

travis/publish.sh
Collected improvements based on testing #163
=> Travis improvements

travis/publish.sh
By the time we do release:prepare and release:perform, tests have
already run and passed.
http://stackoverflow.com/questions/8685100/how-can-i-get-maven-release-plugin-to-skip-my-tests
=> The release plugin needs to be told to skip tests differently

travis/publish.sh
=> Enables maven sync following a successful version tag deployment

zipkin-storage/mysql/README.md
came up in a troubleshooting question from @binlee1990
=> Documents how to lookup a trace using SQL
